version: 2
sources:
  - name: fixture_missing_relations_v2_src
    schema: "fixture_missing_relations_v2_src"
    tables:
      - name: account
      - name: asset
      - name: contact
      - name: opportunity
      - name: project
