version: 2

sources:
  - name: fixture_messy_data_v2_src
    schema: "fixture_messy_data_v2_src"
    tables:
      - name: account
        columns:
          - name: id
          - name: name
          - name: erp_number__c
          - name: customer_tier__c
          - name: region__c
          - name: industry
          - name: website
          - name: billingcity
          - name: billingcountry
          - name: legacy_customer_id__c
      - name: contact
        columns:
          - name: id
          - name: firstname
          - name: lastname
          - name: email
          - name: phone
          - name: title
          - name: role__c
          - name: preferred_language__c
          - name: accountid
      - name: installed_asset__c
        columns:
          - name: id
          - name: name
          - name: serial_number__c
          - name: warranty_end_date__c
          - name: account__c
          - name: project__c
      - name: opportunity
        columns:
          - name: id
          - name: name
          - name: stagename
          - name: closedate
          - name: amount
          - name: currencyisocode
          - name: accountid
      - name: project__c
        columns:
          - name: id
          - name: name
          - name: project_status__c
          - name: go_live_date__c
          - name: account__c
          - name: opportunity__c
