version: 2

sources:
  - name: fixture_missing_relations_src
    schema: fixture_missing_relations_src
    tables:
      - name: Account
      - name: Asset
      - name: Contact
      - name: Opportunity
      - name: Project
