version: 2

sources:
  - name: fixture_missing_relations_v2_src
    database: "{{ target.database }}"
    schema: "fixture_missing_relations_v2_src"
    tables:
      - name: account
        identifier: "account"
      - name: asset
        identifier: "asset"
      - name: contact
        identifier: "contact"
      - name: opportunity
        identifier: "opportunity"
      - name: project
        identifier: "project"
