version: 2
sources:
  - name: fixture_wrong_field_names_v2_src
    description: "Source data from the legacy system for wrong field names v2"
    schema: "fixture_wrong_field_names_v2_src"
    tables:
      - name: ansprechpartner
      - name: assets
      - name: chancen
      - name: kunden
      - name: projects
