name: aidmi_generated
version: '1.0.0'
config-version: 2
profile: aidmi_generated
model-paths: ["models"]
target-path: target
clean-targets: ["target", "dbt_packages"]
models:
  aidmi_generated:
    +materialized: table
