name: 'fixture_master_v2'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

require-dbt-version: [">=1.0.0", "<2.0.0"]
