aidmi_generated:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      dbname: test_db
      schema: public
      threads: 1
      port: 5432
