version: 2

sources:
  - name: fixture_wrong_field_names_v2_src
    schema: "fixture_wrong_field_names_v2_src"
      tables:
        - name: kunden
          identifier: kunden
        - name: ansprechpartner
          identifier: ansprechpartner
        - name: chancen
          identifier: chancen
        - name: proj
          identifier: proj
        - name: assets
          identifier: assets
