
version: 2

sources:
  - name: fixture_master_v2_src
    schema: "fixture_master_v2_src"
    tables:
      - name: master_assets
      - name: master_kontakte
      - name: master_kunden
      - name: master_opportunities
      - name: master_projekte
