version: 2
sources:
  - name: fixture_messy_data_src
    schema: "fixture_messy_data_src"
    tables:
      - name: Account
      - name: Contact
      - name: Installed_Asset__c
      - name: Opportunity
      - name: Project__c
