version: 2

sources:
  - name: fixture_messy_data_v2_src
    schema: "fixture_messy_data_v2_src"
    tables:
      - name: account
      - name: contact
      - name: opportunity
      - name: project__c
      - name: installed_asset__c