version: 2

sources:
  - name: fixture_wrong_field_names_v2_src
    database: "{{ env_var('DBT_DATABASE', 'dbt') }}"
    schema: "fixture_wrong_field_names_v2_src"
    tables:
      - name: kunden
        identifier: kunden
        columns:
          - name: kunden_nr
          - name: firmenname
          - name: erp_nummer
          - name: kategorie
          - name: gebiet
          - name: branche
          - name: webseite
          - name: ort
          - name: land

      - name: ansprechpartner
        identifier: ansprechpartner
        columns:
          - name: ap_id
          - name: vorname
          - name: nachname
          - name: email_adresse
          - name: telefonnummer
          - name: position
          - name: funktion
          - name: sprache
          - name: kunde

      - name: chancen
        identifier: chancen
        columns:
          - name: chance_id
          - name: bezeichnung
          - name: phase
          - name: abschlussdatum
          - name: volumen
          - name: waehrung
          - name: kd_nr

      - name: proj
        identifier: proj
        columns:
          - name: proj_id
          - name: name
          - name: status
          - name: go_live
          - name: kd
          - name: opp

      - name: assets
        identifier: assets
        columns:
          - name: asset_id
          - name: bezeichnung
          - name: seriennr
          - name: garantie_bis
          - name: kd_ref
          - name: projekt_ref
