"""Four CRM->Salesforce migration cases, sharing one target schema.

Sources are committed SQLite DBs read via dlt's sql_database source. Each case
carries a ground_truth.json (from the original _field_mapping) for the
mapping_accuracy evaluator. Artifacts are generated by scripts/import_crm_cases.py.
"""
from pathlib import Path

from aidmi_orchestrator.fixtures.base import Fixture, register_fixture

HERE = Path(__file__).parent
TARGET_SCHEMA = HERE / "target_schema.json"

_EVALUATORS = [
    "execution", "llm_usage", "schema", "manifest_quality",
    "mapping_accuracy", "data_preservation",
]

_CASES = {
    "master": "Full 5-entity CRM migration from German-named tables; value normalization + FK lookups.",
    "wrong_field_names": "Same target as master from German abbreviated table/column names; semantic field-name matching.",
    "messy_data": "Source already target-shaped but dirty (mixed amount/date formats, TEXT amounts); data-quality focus.",
    "missing_relations": "Denormalized source with ambiguous join keys; FK resolution focus.",
}


def _make_source_factory(case: str):
    db_path = HERE / "cases" / case / "source.db"

    def _factory():
        from dlt.sources.sql_database import sql_database
        return sql_database(credentials=f"sqlite:///{db_path}")

    return _factory


for _case, _desc in _CASES.items():
    register_fixture(Fixture(
        name=f"crm_{_case}",
        description=_desc,
        source_factory=_make_source_factory(_case),
        target_schema_path=TARGET_SCHEMA,
        reference_dbt_path=None,
        applicable_evaluators=list(_EVALUATORS),
        ground_truth_mapping_path=HERE / "cases" / _case / "ground_truth.json",
    ))
