version: 2

sources:
  - name: fixture_wrong_field_names_v2_src
    schema: "fixture_wrong_field_names_v2_src"
    tables:
      - name: kunden
        columns:
          - name: kunden_nr
            tests:
              - unique
              - not_null
          - name: firmenname
          - name: erp_nummer
          - name: kategorie
          - name: gebiet
          - name: branche
          - name: webseite
          - name: ort
          - name: land
      - name: ansprechpartner
        columns:
          - name: ap_id
            tests:
              - unique
              - not_null
          - name: vorname
          - name: nachname
          - name: email_adresse
          - name: telefonnummer
          - name: position
          - name: funktion
          - name: sprache
          - name: kunde
      - name: chancen
        columns:
          - name: chance_id
            tests:
              - unique
              - not_null
          - name: bezeichnung
          - name: phase
          - name: abschlussdatum
          - name: volumen
          - name: waehrung
          - name: kd_nr
      - name: proj
        columns:
          - name: proj_id
            tests:
              - unique
              - not_null
          - name: name
          - name: status
          - name: go_live
          - name: kd
          - name: opp
      - name: assets
        columns:
          - name: asset_id
            tests:
              - unique
              - not_null
          - name: bezeichnung
          - name: seriennr
          - name: garantie_bis
          - name: kd_ref
          - name: projekt_ref
