default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      dbname: staging
      schema: target
      threads: 1
      port: 5432