version: 2
sources:
  - name: fixture_wrong_field_names_v2_src
    schema: "fixture_wrong_field_names_v2_src"
    tables:
      - name: ansprechpartner
      - name: assets
      - name: chancen
      - name: kunden
      - name: proj
